/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/bb_froggy.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.head.geometry} material={nodes.head.material} />
      <mesh geometry={nodes.body.geometry} material={nodes.body.material} position={[-0.01, -1.12, 0]} scale={0.57} />
      <mesh
        geometry={nodes.tshirt.geometry}
        material={nodes.tshirt.material}
        position={[-0.01, -1.12, 0]}
        scale={0.6}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[-0.01, -2.25, 0.25]}
        scale={5.86}
      />
    </group>
  )
}

useGLTF.preload('/bb_froggy.glb')
