/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/farmorig.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.ferme01_10_low.geometry} material={nodes.ferme01_10_low.material} />
        <mesh geometry={nodes.ferme01_11_low.geometry} material={nodes.ferme01_11_low.material} />
        <mesh geometry={nodes.ferme01_12_low.geometry} material={nodes.ferme01_12_low.material} />
        <mesh geometry={nodes.ferme01_13_low.geometry} material={nodes.ferme01_13_low.material} />
        <mesh geometry={nodes.ferme01_14_low.geometry} material={nodes.ferme01_14_low.material} />
        <mesh geometry={nodes.ferme01_15_low.geometry} material={nodes.ferme01_15_low.material} />
        <mesh geometry={nodes.ferme01_16_low.geometry} material={nodes.ferme01_16_low.material} />
        <mesh geometry={nodes.ferme01_17_low.geometry} material={nodes.ferme01_17_low.material} />
        <mesh geometry={nodes.ferme01_18_low.geometry} material={nodes.ferme01_18_low.material} />
        <mesh geometry={nodes.ferme01_19_low.geometry} material={nodes.ferme01_19_low.material} />
        <mesh geometry={nodes.ferme01_1_low.geometry} material={nodes.ferme01_1_low.material} />
        <mesh geometry={nodes.ferme01_20_low.geometry} material={nodes.ferme01_20_low.material} />
        <mesh geometry={nodes.ferme01_21_low.geometry} material={nodes.ferme01_21_low.material} />
        <mesh geometry={nodes.ferme01_22_low.geometry} material={nodes.ferme01_22_low.material} />
        <mesh geometry={nodes.ferme01_23_low.geometry} material={nodes.ferme01_23_low.material} />
        <mesh geometry={nodes.ferme01_24_low.geometry} material={nodes.ferme01_24_low.material} />
        <mesh geometry={nodes.ferme01_25_low.geometry} material={nodes.ferme01_25_low.material} />
        <mesh geometry={nodes.ferme01_26_low.geometry} material={nodes.ferme01_26_low.material} />
        <mesh geometry={nodes.ferme01_27_low.geometry} material={nodes.ferme01_27_low.material} />
        <mesh geometry={nodes.ferme01_28_low.geometry} material={nodes.ferme01_28_low.material} />
        <mesh geometry={nodes.ferme01_29_low.geometry} material={nodes.ferme01_29_low.material} />
        <mesh geometry={nodes.ferme01_2_low.geometry} material={nodes.ferme01_2_low.material} />
        <mesh geometry={nodes.ferme01_30_low.geometry} material={nodes.ferme01_30_low.material} />
        <mesh geometry={nodes.ferme01_31_low.geometry} material={nodes.ferme01_31_low.material} />
        <mesh geometry={nodes.ferme01_32_low.geometry} material={nodes.ferme01_32_low.material} />
        <mesh geometry={nodes.ferme01_33_low.geometry} material={nodes.ferme01_33_low.material} />
        <mesh geometry={nodes.ferme01_34_low.geometry} material={nodes.ferme01_34_low.material} />
        <mesh geometry={nodes.ferme01_35_low.geometry} material={nodes.ferme01_35_low.material} />
        <mesh geometry={nodes.ferme01_36_low.geometry} material={nodes.ferme01_36_low.material} />
        <mesh geometry={nodes.ferme01_37_low.geometry} material={nodes.ferme01_37_low.material} />
        <mesh geometry={nodes.ferme01_38_low.geometry} material={nodes.ferme01_38_low.material} />
        <mesh geometry={nodes.ferme01_39_low.geometry} material={nodes.ferme01_39_low.material} />
        <mesh geometry={nodes.ferme01_3_low.geometry} material={nodes.ferme01_3_low.material} />
        <mesh geometry={nodes.ferme01_40_low.geometry} material={nodes.ferme01_40_low.material} />
        <mesh geometry={nodes.ferme01_41_low.geometry} material={nodes.ferme01_41_low.material} />
        <mesh geometry={nodes.ferme01_42_low.geometry} material={nodes.ferme01_42_low.material} />
        <mesh geometry={nodes.ferme01_43_low.geometry} material={nodes.ferme01_43_low.material} />
        <mesh geometry={nodes.ferme01_44_low.geometry} material={nodes.ferme01_44_low.material} />
        <mesh geometry={nodes.ferme01_45_low.geometry} material={nodes.ferme01_45_low.material} />
        <mesh geometry={nodes.ferme01_46_low.geometry} material={nodes.ferme01_46_low.material} />
        <mesh geometry={nodes.ferme01_47_low.geometry} material={nodes.ferme01_47_low.material} />
        <mesh geometry={nodes.ferme01_48_low.geometry} material={nodes.ferme01_48_low.material} />
        <mesh geometry={nodes.ferme01_49_low.geometry} material={nodes.ferme01_49_low.material} />
        <mesh geometry={nodes.ferme01_4_low.geometry} material={nodes.ferme01_4_low.material} />
        <mesh geometry={nodes.ferme01_50_low.geometry} material={nodes.ferme01_50_low.material} />
        <mesh geometry={nodes.ferme01_51_low.geometry} material={nodes.ferme01_51_low.material} />
        <mesh geometry={nodes.ferme01_52_low.geometry} material={nodes.ferme01_52_low.material} />
        <mesh geometry={nodes.ferme01_53_low.geometry} material={nodes.ferme01_53_low.material} />
        <mesh geometry={nodes.ferme01_54_low.geometry} material={nodes.ferme01_54_low.material} />
        <mesh geometry={nodes.ferme01_55_low.geometry} material={nodes.ferme01_55_low.material} />
        <mesh geometry={nodes.ferme01_56_low.geometry} material={nodes.ferme01_56_low.material} />
        <mesh geometry={nodes.ferme01_57_low.geometry} material={nodes.ferme01_57_low.material} />
        <mesh geometry={nodes.ferme01_58_low.geometry} material={nodes.ferme01_58_low.material} />
        <mesh geometry={nodes.ferme01_59_low.geometry} material={nodes.ferme01_59_low.material} />
        <mesh geometry={nodes.ferme01_5_low.geometry} material={nodes.ferme01_5_low.material} />
        <mesh geometry={nodes.ferme01_60_low.geometry} material={nodes.ferme01_60_low.material} />
        <mesh geometry={nodes.ferme01_61_low.geometry} material={nodes.ferme01_61_low.material} />
        <mesh geometry={nodes.ferme01_62_low.geometry} material={nodes.ferme01_62_low.material} />
        <mesh geometry={nodes.ferme01_63_low.geometry} material={nodes.ferme01_63_low.material} />
        <mesh geometry={nodes.ferme01_64_low.geometry} material={nodes.ferme01_64_low.material} />
        <mesh geometry={nodes.ferme01_65_low.geometry} material={nodes.ferme01_65_low.material} />
        <mesh geometry={nodes.ferme01_66_low.geometry} material={nodes.ferme01_66_low.material} />
        <mesh geometry={nodes.ferme01_67_low.geometry} material={nodes.ferme01_67_low.material} />
        <mesh geometry={nodes.ferme01_68_low.geometry} material={nodes.ferme01_68_low.material} />
        <mesh geometry={nodes.ferme01_69_low.geometry} material={nodes.ferme01_69_low.material} />
        <mesh geometry={nodes.ferme01_6_low.geometry} material={nodes.ferme01_6_low.material} />
        <mesh geometry={nodes.ferme01_70_low.geometry} material={nodes.ferme01_70_low.material} />
        <mesh geometry={nodes.ferme01_71_low.geometry} material={nodes.ferme01_71_low.material} />
        <mesh geometry={nodes.ferme01_72_low.geometry} material={nodes.ferme01_72_low.material} />
        <mesh geometry={nodes.ferme01_73_low.geometry} material={nodes.ferme01_73_low.material} />
        <mesh geometry={nodes.ferme01_74_low.geometry} material={nodes.ferme01_74_low.material} />
        <mesh geometry={nodes.ferme01_75_low.geometry} material={nodes.ferme01_75_low.material} />
        <mesh geometry={nodes.ferme01_76_low.geometry} material={nodes.ferme01_76_low.material} />
        <mesh geometry={nodes.ferme01_77_low.geometry} material={nodes.ferme01_77_low.material} />
        <mesh geometry={nodes.ferme01_78_low.geometry} material={nodes.ferme01_78_low.material} />
        <mesh geometry={nodes.ferme01_79_low.geometry} material={nodes.ferme01_79_low.material} />
        <mesh geometry={nodes.ferme01_7_low.geometry} material={nodes.ferme01_7_low.material} />
        <mesh geometry={nodes.ferme01_80_low.geometry} material={nodes.ferme01_80_low.material} />
        <mesh geometry={nodes.ferme01_81_low.geometry} material={nodes.ferme01_81_low.material} />
        <mesh geometry={nodes.ferme01_82_low.geometry} material={nodes.ferme01_82_low.material} />
        <mesh geometry={nodes.ferme01_83_low.geometry} material={nodes.ferme01_83_low.material} />
        <mesh geometry={nodes.ferme01_84_low.geometry} material={nodes.ferme01_84_low.material} />
        <mesh geometry={nodes.ferme01_85_low.geometry} material={nodes.ferme01_85_low.material} />
        <mesh geometry={nodes.ferme01_86_low.geometry} material={nodes.ferme01_86_low.material} />
        <mesh geometry={nodes.ferme01_87_low.geometry} material={nodes.ferme01_87_low.material} />
        <mesh geometry={nodes.ferme01_88_low.geometry} material={nodes.ferme01_88_low.material} />
        <mesh geometry={nodes.ferme01_89_low.geometry} material={nodes.ferme01_89_low.material} />
        <mesh geometry={nodes.ferme01_8_low.geometry} material={nodes.ferme01_8_low.material} />
        <mesh geometry={nodes.ferme01_90_low.geometry} material={nodes.ferme01_90_low.material} />
        <mesh geometry={nodes.ferme01_91_low.geometry} material={nodes.ferme01_91_low.material} />
        <mesh geometry={nodes.ferme01_92_low.geometry} material={nodes.ferme01_92_low.material} />
        <mesh geometry={nodes.ferme01_93_low.geometry} material={nodes.ferme01_93_low.material} />
        <mesh geometry={nodes.ferme01_94_low.geometry} material={nodes.ferme01_94_low.material} />
        <mesh geometry={nodes.ferme01_9_low.geometry} material={nodes.ferme01_9_low.material} />
        <mesh geometry={nodes.ferme01__low.geometry} material={nodes.ferme01__low.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/farmorig.glb')
